### ISSUE TITLE
[BUILD]:Add a theme dir in /src/styles

### ISSUE THREAD

**Issue by DugarRishab** [DugarRishab/prism-ui#2]
## description 
Add 2 files - themes.css and themes.js files in the dir - /src/styles from the colors given in this [Figma Design File](https://www.figma.com/file/Xt6KCBKsXRKRImaVHQebca/pui-components?type=design&nodeid=0%3A1&mode=design&t=XcF33hdl14DkyLKT-1)

### theme.js file - 
It exports 3 themes - color, black and white. A theme consists -  
- the primary color, 
  - primary-dark
  - primary-light
- the font color, 
  - font-default
  - font-disabled
  - font-error (generally a red hue)
  - font-success (generally a green hue)
  - font-link
- the paper color (generally primary-dark, or primary with 10%-20% opacity)
- the default padding and margins
- box-shadows

### theme.css

same thing as [above](/#theme.js) but in css in the `::root` section 

## Proposal- 
Give a small proposal describing your method of implementation. 

## checklist
- [ ] added a themes.css file
- [ ] added a themes.js file which exports all the themes.

**Comment by rohit62043** [comment]
I want to work on this issue @DugarRishab
