### ISSUE TITLE
[DESIGN]: Design Avatar components on Figma. 

### ISSUE THREAD

**Issue by DugarRishab** [DugarRishab/prism-ui#5]
## Description

Design components for prism-ui (pui) on Figma using the [COMPONENT_GUIDELINES](https://github.com/DugarRishab/prism-ui/blob/main/COMPONENT_GUIDELINES.md) and taking examples from the components already made in the Figma file. The edit-access link will not be made public. Instead, if you want to work on this, comment down here with your email address linked to your Figma account. 

## Checklist
- [ ] Design a single Avatar component
- [ ] Design grouped-Avatar components. See [this](https://mui.com/material-ui/react-avatar/) for reference
- [ ] Design an Avatar component with a DP in case a user does not have an image. 
- [ ] Design three different themes for this component, as will be shown in the Figma file. 
- [ ] Give proper text boxes in case you want to mention something.

**Comment by Kripu-star** [comment]
I would like to contribute.
pushpamkumari3122@gmail.com

**Comment by DugarRishab** [comment]
> I would like to contribute. [pushpamkumari3122@gmail.com](mailto:pushpamkumari3122@gmail.com)

@Kripu-star giving you access to figma and assigning you this issue.

**Comment by Kripu-star** [comment]
@DugarRishab 

I’ve completed the designs for the Avatar component.

**Comment by DugarRishab** [comment]
> @DugarRishab
> 
> I’ve completed the designs for the Avatar component.

I have attached some comments on your work, please check them out. The goal of this issue was to teach u the basics of Figma for further more complex tasks, so please complete them properly.
